# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Swabbr' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Swabbr
  pod 'SwiftyCam'
  pod 'NextLevel', '0.14.0'
  pod 'Cache'
  pod 'Imaginary'
  
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'Firebase/Messaging'

end
